#include <array>
#include <charconv>
#include <concepts>
#include <filesystem>
#include <fmt/color.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <fstream>
#include <iostream>
#include <memory>
#include <optional>
#include <range/v3/algorithm.hpp>
#include <range/v3/view.hpp>
#include <regex>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/spdlog.h>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>
